services:
  node:
    image: node-dev:custom
    container_name: node-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/development:rw
    expose:
      - 4000
    ports:
      - 4000:4000
    #command: node index.js
