services:
  postgre:
    image: my_postgres:custom
    container_name: my_postgre_15
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: