FROM node:18-alpine

ENV PROJECT_DIR=development 

RUN apk add --no-cache libc6-compat
RUN apk add git
RUN apk add vim 

RUN mkdir -p /home/$PROJECT_DIR

WORKDIR /home/$PROJECT_DIR

COPY . .
VOLUME /home/$PROJECT_DIR
RUN chown -R node:node /home/$PROJECT_DIR

USER node